# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  api:
    depends_on:
      postgres: 
        condition: service_started
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=VietConnect
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  app_data:
